### ISSUE TITLE
How to upgrade project to latest version of flex-template correctly?

### ISSUE THREAD

**Issue by ZhenWang-Jen** [sharetribe/flex-template-web#1110]
**Description** I have a project with version 2.7 of flex-template-web. Now I want to upgrade to the latest version. Is there anything official way of doing it?

**To Reproduce** Steps to reproduce the behavior:

1. Go to package.json.
2. Change the version to 2.17.
3. Save the change and run "yarn install".
4. Still old versions of sharetribe SDK and scripts.

**Expected behavior** A clear script to upgrade to the latest version.

**Screenshots**
yarn.lock after installing dependecies:
![image](https://user-images.githubusercontent.com/28586492/58909736-b2089980-86c8-11e9-9ecb-065e0a96498c.png)

Thanks!

**Comment by Gnito** [comment]
Hi @ZhenWang-Jen!

and sorry for a slow response. We had a bit lightweight development shifts last week. If you want to get faster responses - it's probably better to ask through chat widget in Console or through Slack.

Anyway, this can be done with git commands already.

First, you should check your remote branches with `git remote -v`. If you have a branch called upstream that points to FTW repository, you are fully configured.
https://help.github.com/en/articles/configuring-a-remote-for-a-fork

After that, you can just fetch upstream changes and merge certain release tag.
`git fetch upstream`
`git merge upstream/v2.17.0`
https://www.sharetribe.com/docs/guides/how-to-customize-ftw/#pull-in-latest-upstream-changes

The biggest issue with this workflow is merge conflicts. If you have made changes to those lines, which are also touched in upstream (in this repo), it will create conflicts that need to be resolved. So, the problem is inherent with this approach. FTW is essentially a template / starting point for creating your own client app. 

If you want to stay in sync with changes made in this repository, I'd recommend that you try to take updates often - it is easier to resolve possible conflicts if there are fewer files that are touched. (And yes, there are still missing features from this template - which makes upstream updates an entirely valid course of action.)
