### ISSUE TITLE
.env config

### ISSUE THREAD

**Issue by CryptoKR** [sharetribe/flex-template-web#849]
What do I put for these variables in env file?

**Comment by CryptoKR** [comment]
# Mandatory configuration
#
REACT_APP_SHARETRIBE_SDK_CLIENT_ID=
REACT_APP_GOOGLE_MAPS_API_KEY=
REACT_APP_STRIPE_PUBLISHABLE_KEY=

**Comment by CryptoKR** [comment]
Where do I find SHARETRIBE_SDK_CLIENT_ID??

**Comment by rap1ds** [comment]
Hi there! Thanks for your interest to Sharetribe Flex!

Sharetribe Flex is currently in Closed Preview mode. This means that we are currently unable to open the access to everyone. We will be handing out API keys slowly to more and more people.

In order to get your API key, I'd suggest you to [Request early access](https://www.sharetribe.com/flex/), keeping in mind that you may need to wait some time to get the API key, or you may be even rejected from the early access. This is unfortunate, but as mentioned, we are not yet able to open Flex to everyone who is interested.
