### ISSUE TITLE
Change in Google Maps pricing and potential impacts for costs

### ISSUE THREAD

**Issue by thomasmalbaux** [sharetribe/flex-template-web#875]
On July 16th, Google updated their pricing for the use of their Google Maps services. Maybe you’ve noticed it already or have been contacted by Google. You can [learn more about it in this article](https://cloud.google.com/maps-platform/pricing/sheet/) and [get an estimate of your monthly costs here](https://mapsplatformtransition.withgoogle.com/calculator).

This means that, if you use the Google Maps provided in the Flex Template for Web with your own Maps API Key, your Google Maps bill will most likely increase. The exact costs depend on quite a lot of parameters and on your volume, but in general this is a significant raise and costs might be in the thousands of $ quite fast, as you grow.

We’ve already started to work out different ways to limit the impact of Google’s decision on your business and growth.

## What we are working on already
We started to make changes to the Flex Template for Web to reduce the number of calls to the Google Maps API:

We started to use [session tokens](https://developers.google.com/maps/documentation/javascript/places-autocomplete#session_tokens) on the _LocationAutocompleteInput_ component and reduced place details calls to [SKU basic data](https://developers.google.com/maps/billing/understanding-cost-of-use?__utma=236542612.592594166.1531226593.1532512294.1532512294.1&__utmb=236542612.0.10.1532512294&__utmc=236542612&__utmx=-&__utmz=236542612.1532512294.1.1.utmcsr=(direct)%7Cutmccn=(direct)%7Cutmcmd=(none)&__utmv=-&__utmk=124971081&_ga=2.125534414.-592594166.1531226593#basic-data).
We also changed the map on _ListingPage_ to be initially a static map (but if clicked it will be changed to a dynamic map). That map is also not loaded if a user doesn't scroll to that part of the page.

We are still experimenting what could be done to the dynamic map on _SearchPage_ and if the current changes are reducing the costs enough. 

## What changes to your front end you should consider
_ListingPage_: think about using [embedded map](https://developers.google.com/maps/documentation/embed/start) instead of static or dynamic map or at least move the map to the bottom of the main column.
_SearchPage_: think about adding a toggle for the map on _SearchPage_. We are also considering making this change to the Flex Template for Web.

We’ll continue to bring improvements about this in the coming days and weeks, so don’t hesitate to monitor the [FTW repository](https://github.com/sharetribe/flex-template-web) and update your project from upstream.

## What we are considering to do next
Even with optimized use of the Google Maps API, it might be quite challenging in the future to rely on this solution.

We are discussing with Google Partners to learn more, and are also considering other solutions.
Nothing is decided yet however we may consider integrating another map provider if one with a more reasonable pricing model is found.

## What you should keep in mind
If you are now building customizations related to Google Maps, you might want to look at potential impacts on your Google Maps bills.

It’s also good to keep in mind that we may introduce other map providers in the future.

## Let us know about your experience
If this raises any question or if you’d like to share your own experience with the Google Maps pricing change, feel free to share!

**Comment by Gnito** [comment]
We ended up making several improvements to Google Maps version:
- Default predictions to reduce place details calls (LocationAutocomplete)
- Set timeout to prediction fetches whit small character count (LocationAutocomplete)
- Use only basic fields in place details call (LocationAutocomplete)
- Use session tokens (LocationAutocomplete)
- Use static map by default. User needs to click the map to get dynamic map (ListingPage/Map)
- Lazy load Map component only if the viewport is close after scrolling (ListingPage/Map)
- Reusable map aka load the search map only once per page refresh "session" (SearchMap)

- **Future:** we are planning to remove LocationAutocomplete from hero section on landing page. It is better UX for new marketplaces to have call-to-action link that leads directly to a preselected city / country where there are listings instead of a place of user's own choosing.

However, those improvements were not enough for some marketplace concepts - the pricing was still quite high. So, **the current version (v2.0.0) is now configured to be integrated to [Mapbox](https://github.com/sharetribe/flex-template-web/blob/master/docs/map-providers.md).** Google Map is still supported and there are [a guide how to change to that](https://github.com/sharetribe/flex-template-web/blob/master/docs/google-maps.md).

Other map providers:
The default map setup of Flex template app uses library called `mapbox-gl-js`. It is supported by quite many other map providers too. Thus, if you wish to use a map provider other than Google Maps or Mapbox, first check if the map provider you are considering is supporting this library. If they are, the change might be quite easy. Note: if you change the map tile provider you should also change geocoding API too (i.e. the API endpoint for LocationAutocompleteInput component).
